### ISSUE TITLE
Include `block.clock.id` to `State`

### ISSUE THREAD

**Issue by DenisCarriere** [substreams-js/substreams-js#17]
Perhaps we can include include `clock` in State

## Before

```typescript
export type State = {
  current: bigint;
  cursor: string | undefined;
  timestamp: Date | undefined;
  modules: {
    [key: string]: ModuleState;
  };
};
```

## Proposal A

```typescript
export type State = {
  current: bigint; // Current Block Number
  id?: string; // Block ID
  cursor?: string;
  timestamp?: Date;
  modules: {
    [key: string]: ModuleState;
  };
};
```

## Proposal B

```typescript
export type State = {
  current: bigint;
  cursor?: string;
  clock?: Clock;
  modules: {
    [key: string]: ModuleState;
  };
};
```

**Comment by fubhy** [comment]
@DenisCarriere I'm thinking about dropping the cursor and clock from the state entirely and only use it to track module progress. Thoughts?

It's rather simple to record the latest clock & cursor in consumer land, no?

**Comment by fubhy** [comment]
Done ... We'll get server-side state tracking soon so it'll make even less sense to do all that tracking locally. Instead, ppl should just pull the cursor from the `blockScopedData` payloads.
