### ISSUE TITLE
Add `applyParams` testcase for (allow `=` character)

### ISSUE THREAD

**Issue by DenisCarriere** [substreams-js/substreams-js#33]
Allow `=` to be included as param value

> split using `.split(/=(.*)/s)` Regex pattern

- [ ] "mymodule=A=B"
  - [ ] `module` => "mymodule"
  - [ ] `value` => "A=B"
- [ ] add Unit tests

https://github.com/substreams-js/substreams-js/blob/main/packages/core/src/manifest/params/apply-params.test.ts

```typescript
> "mymodule=A=B".split("=",2)
[ 'mymodule', 'A' ]

> "mymodule=A=B".split("=")
[ 'mymodule', 'A', 'B' ]

> "mymodule=A=B".split(/=(.*)/s)
[ 'mymodule', 'A=B', '' ]
```

**Comment by chamorin** [comment]
Opened a [PR](https://github.com/substreams-js/substreams-js/pull/34) related to that issue
