### ISSUE TITLE
Importance of protobuf files ordering in `substreams.yaml` manifest

### ISSUE THREAD

**Issue by catalyst17** [substreams-js/substreams-js#54]
When using this library I've noticed it cannot create registry properly when the order of `protobuf.files` in the manifest is not strict.

As for example, consider a definition that imports other definitions from neighbouring files. And if the imported ones (e.g. `op_rollup.proto` or `nitro_rollup.proto`) are stated after the one that does the import (e.g. `combined_rollups.proto`), then such an error will be raised:
```
invalid FieldDescriptorProto: type_name .<CUSTOM_PKG>.NitroRollup not found"
```

So in order to fix it I had to repack the `.SPKG` by changing the manifest file from this:
```proto3
protobuf:
  files:
    - combined_rollups.proto
    - op_rollup.proto
    - nitro_rollup.proto
  importPaths:
    - ./proto
``` 
to this:
```proto3
protobuf:
  files:
    - op_rollup.proto
    - nitro_rollup.proto
    - combined_rollups.proto
  importPaths:
    - ./proto
``` 

I've done a bit of debugging and found that this happens in `create-descriptor-set.js:447` in `newField()` because of `cart.mapEntries` doesn't yet have the child definitions added.

The substreams package itself doesn't seem to break in such a case if used directly through `substreams` CLI. But this library does break because of that.

If this cannot be easily fixed I suggest at least adding some ⚠️ info in the README :)

Rather than that, thanks for a very useful library!

**Comment by fubhy** [comment]
That's a bug then! We strive for compatibility with the `Go` substreams toolchain. I'll try to fix this tomorrow.

**Comment by fubhy** [comment]
This is actually imho a bug in the substreams cli. The file descriptors should be sorted in topological order in the packages substreams.spkg. In fact, I'm now wondering why it's even necessary to list out all the protobuf files in the substreams.yaml to begin with and not rely on the native import resolution in those files (e.g. only specifiy the root .proto entrypoint and have the ecosystem-native protobuf parser resolve imports).

Can you raise this with the StreamingFast folks?

./cc @sduchesneau Can you provide insight why this is set up in this manner in the first place? :-)

**Comment by fubhy** [comment]
This opinion seems to be shared by the `protobuf-es` package authors:

https://github.com/bufbuild/protobuf-es/blob/5ee26a1f465af8a2ea703a9aa9ac21758a87ccbb/packages/protobuf/src/create-descriptor-set.ts#L61-L69

**Comment by catalyst17** [comment]
The CLI is handling it properly even when running it against the package like this:
```
substreams run -e $(ENDPOINT) <NAME>.spkg map_combine_rollups -s $(START_BLOCK) -t $(STOP_BLOCK)
```

But I assume you meant the actual `pack` command itself? That in order to be properly handled by consumers other than the `substreams` CLI it should be specifying the descriptors in the topological order?

**Comment by fubhy** [comment]
> The CLI is handling it properly even when running it against the package like this:
> 
> ```
> substreams run -e $(ENDPOINT) <NAME>.spkg map_combine_rollups -s $(START_BLOCK) -t $(STOP_BLOCK)
> ```
> 
> But I assume you meant the actual `pack` command itself? That in order to be properly handled by consumers other than the `substreams` CLI it should be specifying the descriptors in the topological order?

Yes, correct. The package should be produced with the protobuf files in topological order.

Btw., do you even have to specify all .proto files in that list? Doesn't it automatically resolve `import` statements from the .proto files?

**Comment by fubhy** [comment]
If you don't specify anything though it will not bundle any protobuf file descriptors with the .spkg file and therefor not let you derive a protobuf registry for decoding at runtime. That means you won't be able to decode any of the binary output of the substream unless you "bring your own" registry that is compatible with your particular substream. That's possible but will leave the .spkg less portable of course.

**Comment by sduchesneau** [comment]
This PR https://github.com/substreams-js/substreams-js/pull/68 reorders the protobuf files topologically on-the-fiy, like the go implementation does.

Future packages packed with substreams cli will have the correct order.
Does that fix your issue ?

**Comment by maoueh** [comment]
Closing as this should be fixed everywhere now (Substreams CLI and in the library).

Re-open if you any further issue.
